-- ============================================
-- 创建球队翻译表（i18n）
-- 用于分离原始英文数据和翻译数据
-- ============================================

-- 1. 创建翻译表
CREATE TABLE IF NOT EXISTS fd_teams_i18n (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    team_id INTEGER NOT NULL,  -- 关联 fd_teams.fd_id
    lang_code VARCHAR(10) NOT NULL,  -- 语言代码: zh-CN, en, ja 等
    name_translated TEXT NOT NULL,  -- 翻译后的队名
    short_name_translated TEXT,  -- 翻译后的短名称
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- 唯一约束：每个球队的每种语言只能有一条翻译
    CONSTRAINT teams_i18n_unique UNIQUE (team_id, lang_code),

    -- 外键关联
    CONSTRAINT teams_i18n_team_fkey FOREIGN KEY (team_id)
        REFERENCES fd_teams(fd_id) ON DELETE CASCADE
);

-- 2. 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_teams_i18n_team_id ON fd_teams_i18n(team_id);
CREATE INDEX IF NOT EXISTS idx_teams_i18n_lang_code ON fd_teams_i18n(lang_code);

-- 3. 添加注释
COMMENT ON TABLE fd_teams_i18n IS '球队多语言翻译表，分离原始数据和翻译数据';
COMMENT ON COLUMN fd_teams_i18n.team_id IS '关联的球队ID (fd_teams.fd_id)';
COMMENT ON COLUMN fd_teams_i18n.lang_code IS '语言代码，如 zh-CN, en, ja';
COMMENT ON COLUMN fd_teams_i18n.name_translated IS '翻译后的球队名称';
COMMENT ON COLUMN fd_teams_i18n.short_name_translated IS '翻译后的短名称';
