-- 创建竞彩比赛表
CREATE TABLE IF NOT EXISTS sporttery_matches (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    match_code TEXT NOT NULL UNIQUE,
    group_date TEXT,
    home_team TEXT NOT NULL,
    away_team TEXT NOT NULL,
    league TEXT NOT NULL,
    match_time TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    actual_score TEXT,
    half_score TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_sporttery_matches_date ON sporttery_matches(group_date);
CREATE INDEX IF NOT EXISTS idx_sporttery_matches_status ON sporttery_matches(status);
CREATE INDEX IF NOT EXISTS idx_sporttery_matches_time ON sporttery_matches(match_time);

-- 添加注释
COMMENT ON TABLE sporttery_matches IS '中国竞彩官方比赛数据';
COMMENT ON COLUMN sporttery_matches.match_code IS '比赛编号（官方唯一标识）';
COMMENT ON COLUMN sporttery_matches.group_date IS '比赛日期（分组）';
COMMENT ON COLUMN sporttery_matches.home_team IS '主队';
COMMENT ON COLUMN sporttery_matches.away_team IS '客队';
COMMENT ON COLUMN sporttery_matches.league IS '联赛';
COMMENT ON COLUMN sporttery_matches.match_time IS '比赛时间';
COMMENT ON COLUMN sporttery_matches.status IS '状态: pending/finished';
COMMENT ON COLUMN sporttery_matches.actual_score IS '全场比分';
COMMENT ON COLUMN sporttery_matches.half_score IS '半场比分';
